### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by exeldro** [admshao/obs-transition-matrix#1]
With OBS 22.0.2 and plugin version Beta Build V1.0-beta1 I see the following in the log:
15:08:41.702: LoadLibrary failed for '../../obs-plugins/64bit/obs-transition-matrix.dll': (null) (127)
15:08:41.702: Module '../../obs-plugins/64bit/obs-transition-matrix.dll' not loaded

**Comment by admshao** [comment]
I've updated the released file this time built with same QT version as OBS Release. Sorry for the trouble
