### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by clvrk** [admshao/obs-transition-matrix#4]
Hello!

When I open up OBS Studio I couldn't find the "Transition Override Matrix" tab in the "Tools" section. After checking my logs I found a line that says the following:
```
Module '../../obs-plugins/64bit/obs-transition-matrix.dll' not loaded
```
Are there any special (runtime) dependencies that the plugin requires?
I'm on Windows 10 Pro 64-bit, OBS Studio 24.0.3 (64-bit), downloaded from the latest release (_OBS Transition Matrix V1.0_), so not build from source.

Thank you :-)

**Comment by E-Thorpe** [comment]
I'm having the same problems as well. The same operating system, same version of OBS as well.

**Comment by admshao** [comment]
Plugin was built with Qt 5.14 while OBS Studio still uses 5.10.1.

I'll provide a fresh build soon

**Comment by admshao** [comment]
Release updated. Should be fixed now

**Comment by ochen1** [comment]
```
error: os_dlopen(~/.config/obs-studio/plugins/obs-transition-matrix/bin/64bit/obs-transition-matrix.so->~/.config/obs-studio/plugins/obs-transition-matrix/bin/64bit/obs-transition-matrix.so): /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.14' not found (required by ~/.config/obs-studio/plugins/obs-transition-matrix/bin/64bit/obs-transition-matrix.so)

warning: Module '~/.config/obs-studio/plugins/obs-transition-matrix/bin/64bit/obs-transition-matrix.so' not loaded
```
The Linux version of the build appears to be still using Qt 5.14. Am I the only one experiencing this?

**Comment by ochen1** [comment]
Nevermind, I compiled it myself.

Followed the instructions here https://github.com/CatxFish/obs-v4l2sink/issues/54
Even though its for a totally different project, it worked with minor modifications

Now, in case anyone else needs it, I've attached my compiled version below. :tada: 

[obs-transition-matrix.zip](https://github.com/admshao/obs-transition-matrix/files/5252376/obs-transition-matrix.zip)
